// FUNCTION BOARDMEMBER(NAME, HOMESTATE, TRAINING){
//   THIS.NAME = NAME
//   THIS.HOMESTATE = HOMESTATE
//   THIS.TRAINING = TRAINING
//
//   THIS.VETO = FUNCTION(){
//     RETURN 'NO, I MUST DISAGREE'
//   }
//   THIS.APPROVE = FUNCTION(){
//     RETURN 'YOU CAN DO THAT!'
//   }
//   THIS.DOCHARITY = FUNCTION(){
//     RETURN "I LIKE TO HELP PEOPLE."
//   }
//
//   THIS.RELEASEPRESSSTATEMENT = FUNCTION(){
//     RETURN "YOU WILL SEE GREAT THINGS FROM SCUBER."
//   }
//
//   THIS.SAYHI = FUNCTION(){
//     RETURN `HI, MY NAME IS ${THIS.NAME}. I AM FROM ${THIS.HOMESTATE}, AND I WAS TRAINED IN ${THIS.TRAINING}.`
//   }
// }
